
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'PT' | 'EN' | 'ES';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  PT: {
    nav_home: 'HOME',
    nav_schools: 'ESCOLAS',
    nav_team: 'TEAM',
    nav_store: 'STORE',
    nav_contact: 'CONTATO',
    hero_elevate: 'ELEVE O',
    hero_jiujitsu: 'DO SEU JIU JITSU',
    hero_desc: 'Onde a tradição encontra a modernidade. Experimente o padrão LEVEL de ensino em um ambiente exclusivo desenhado para a sua evolução soberana.',
    hero_btn_units: 'ENCONTRAR UNIDADE',
    hero_btn_team: 'CONHECER O TIME',
    stats_students: 'Alunos Ativos',
    stats_years: 'De Experiência',
    stats_champs: 'Títulos',
    bb_kicker: 'ELITE DA EQUIPE',
    bb_title_prefix: 'Uma equipe com',
    bb_title_gold: 'muitos faixas pretas.',
    bb_desc: 'Para dar uma ideia da nossa base, aqui vai uma vitrine com os destaques e a força do time.',
    bb_total_label: 'Faixas pretas',
    bb_total_value: '50+',
    bb_activity_label: 'Em atividade',
    bb_activity_value: 'Alta',
    bb_rank_title: 'Destaque do Time',
    bb_rank_name: 'Nome do Faixa Preta',
    bb_rank_sub: 'Faixa Preta',
    bb_hint: 'Quer ver a lista completa e os professores? Clique em "Saiba mais".',
    bb_cta: 'Saiba mais',
    bb_ranking_title: 'RANKING',
    bb_ranking_top: 'Lider',
    founders_title: 'NOSSOS FUNDADORES',
    founders_subtitle: 'A LINHAGEM DA SOBERANIA',
    founder_age: 'Idade',
    founder_rank: 'Graduação',
    founder_bio: 'Bio',
    action_affiliate_title: 'QUERO SER',
    action_affiliate_span: 'AFILIADO',
    action_affiliate_desc: 'Leve a soberania LEVEL para sua cidade e transforme sua academia em um centro de autoridade internacional.',
    action_student_title: 'QUERO SER',
    action_student_span: 'ALUNO',
    action_student_desc: 'Inicie sua jornada na elite do Jiu Jitsu com instrutores mestres e um ambiente de alto padrão.',
    units_title: 'REFERÊNCIA',
    units_span: 'NACIONAL',
    units_presence: 'NOSSAS UNIDADES',
    units_btn_all: 'VER TODAS UNIDADES',
    map_locator: 'LOCALIZADOR DE ELITE',
    map_vibe: 'VIVA O PADRÃO',
    map_desc: 'Presente na região de Campinas e Jaguariúna. Encontre a unidade LEVEL mais próxima e faça parte da nossa comunidade.',
    map_placeholder: 'Sua localização (Cidade ou CEP)',
    map_btn_search: 'BUSCAR',
    map_open_maps: 'ABRIR NO GOOGLE MAPS',
    map_no_results: 'Nenhuma unidade encontrada.',
    store_title: 'LEVEL',
    store_span: 'STORE',
    store_buy: 'COMPRAR AGORA',
    store_filiais: 'À VENDA NAS FILIAIS',
    store_explore: 'EXPLORAR TODA A COLEÇÃO',
    philosophy_title: 'Filosofia soberana',
    philosophy_text: 'NÃO É SÓ SOBRE LUTAR.',
    philosophy_sub: 'É SOBRE ALCANÇAR A MAESTRIA.',
    philosophy_message: 'Desenvolvimento no tatame, transformação na vida',
    news_title: 'FIQUE POR DENTRO DO',
    news_desc: 'Assine nossa newsletter exclusiva e receba notícias sobre eventos de elite e novos lançamentos.',
    news_placeholder: 'Seu melhor e-mail',
    news_btn: 'INSCREVER',
    footer_desc: 'Elevando o padrão global através de uma metodologia de elite e um lifestyle focado na soberania humana.',
    footer_nav: 'NAVEGAÇÃO',
    footer_corp: 'CORPORATIVO',
    footer_rights: 'LEVEL JIU JITSU GLOBAL. SOBERANIA & TRADIÇÃO.'
  },
  EN: {
    nav_home: 'HOME',
    nav_schools: 'SCHOOLS',
    nav_team: 'TEAM',
    nav_store: 'STORE',
    nav_contact: 'CONTACT',
    hero_elevate: 'ELEVATE YOUR',
    hero_jiujitsu: 'ON JIU JITSU',
    hero_desc: 'Where tradition meets modernity. Experience the LEVEL standard of teaching in an exclusive environment designed for your sovereign evolution.',
    hero_btn_units: 'FIND A UNIT',
    hero_btn_team: 'MEET THE TEAM',
    stats_students: 'Active Students',
    stats_years: 'Years of Experience',
    stats_champs: 'Titles',
    bb_kicker: 'TEAM ELITE',
    bb_title_prefix: 'A team with',
    bb_title_gold: 'many black belts.',
    bb_desc: 'To give you a sense of our base, here is a showcase with highlights and the strength of the team.',
    bb_total_label: 'Black belts',
    bb_total_value: '50+',
    bb_activity_label: 'Active',
    bb_activity_value: 'High',
    bb_rank_title: 'Team Highlight',
    bb_rank_name: 'Black Belt Name',
    bb_rank_sub: 'Black Belt',
    bb_hint: 'Want the full list and instructors? Click "Learn more".',
    bb_cta: 'Learn more',
    bb_ranking_title: 'RANKING',
    bb_ranking_top: 'Leader',
    founders_title: 'OUR FOUNDERS',
    founders_subtitle: 'THE SOVEREIGNTY LINEAGE',
    founder_age: 'Age',
    founder_rank: 'Rank',
    founder_bio: 'Bio',
    action_affiliate_title: 'BECOME AN',
    action_affiliate_span: 'AFFILIATE',
    action_affiliate_desc: 'Bring LEVEL sovereignty to your city and transform your academy into an international center of authority.',
    action_student_title: 'BECOME A',
    action_student_span: 'STUDENT',
    action_student_desc: 'Start your journey in the Jiu Jitsu elite with master instructors and a high-standard environment.',
    units_title: 'NATIONAL',
    units_span: 'REFERENCE',
    units_presence: 'OUR UNITS',
    units_btn_all: 'VIEW ALL UNITS',
    map_locator: 'ELITE LOCATOR',
    map_vibe: 'LIVE THE',
    map_desc: 'Present in the Campinas and Jaguariúna region. Find your nearest LEVEL unit and join our community.',
    map_placeholder: 'Your location (City or ZIP)',
    map_btn_search: 'SEARCH',
    map_open_maps: 'OPEN IN GOOGLE MAPS',
    map_no_results: 'No units found.',
    store_title: 'LEVEL',
    store_span: 'STORE',
    store_buy: 'BUY NOW',
    store_filiais: 'AVAILABLE AT OUR BRANCHES',
    store_explore: 'EXPLORE FULL COLLECTION',
    philosophy_title: 'sovereign philosophy',
    philosophy_text: 'IT\'S NOT JUST ABOUT FIGHTING.',
    philosophy_sub: 'IT\'S ABOUT ACHIEVING MASTERY.',
    philosophy_message: 'level — development on the mats, transformation in life',
    news_title: 'STAY INSIDE THE',
    news_desc: 'Subscribe to our exclusive newsletter and receive news about elite events and new releases.',
    news_placeholder: 'Your best e-mail',
    news_btn: 'SUBSCRIBE',
    footer_desc: 'Elevating the global standard through an elite methodology and a lifestyle focused on human sovereignty.',
    footer_nav: 'NAVIGATION',
    footer_corp: 'CORPORATE',
    footer_rights: 'LEVEL JIU JITSU GLOBAL. SOVEREIGNTY & TRADITION.'
  },
  ES: {
    nav_home: 'INICIO',
    nav_schools: 'ESCUELAS',
    nav_team: 'EQUIPO',
    nav_store: 'TIENDA',
    nav_contact: 'CONTACTO',
    hero_elevate: 'ELEVA EL',
    hero_jiujitsu: 'DE TU JIU JITSU',
    hero_desc: 'Donde la tradición se encuentra con la modernidade. Experimenta el estándar LEVEL de enseñanza en un ambiente exclusivo diseñado para tu evolución soberana.',
    hero_btn_units: 'ENCONTRAR UNIDAD',
    hero_btn_team: 'CONOCER EL EQUIPO',
    stats_students: 'Alumnos Activos',
    stats_years: 'Años de Experiencia',
    stats_champs: 'Títulos',
    bb_kicker: 'ELITE DEL EQUIPO',
    bb_title_prefix: 'Un equipo con',
    bb_title_gold: 'muchos cinturones negros.',
    bb_desc: 'Para darte una idea de nuestra base, aqui va una vitrina con los destacados y la fuerza del equipo.',
    bb_total_label: 'Cinturones negros',
    bb_total_value: '50+',
    bb_activity_label: 'En actividad',
    bb_activity_value: 'Alta',
    bb_rank_title: 'Destacado del Equipo',
    bb_rank_name: 'Nombre del Cinturón Negro',
    bb_rank_sub: 'Cinturón Negro',
    bb_hint: '¿Quieres ver la lista completa y los profesores? Haz clic en "Saber más".',
    bb_cta: 'Saber más',
    bb_ranking_title: 'RANKING',
    bb_ranking_top: 'Lider',
    founders_title: 'NUESTROS FUNDADORES',
    founders_subtitle: 'EL LINAJE DE LA SOBERANÍA',
    founder_age: 'Edad',
    founder_rank: 'Graduación',
    founder_bio: 'Bio',
    action_affiliate_title: 'QUIERO SER',
    action_affiliate_span: 'AFILIADO',
    action_affiliate_desc: 'Lleva la soberanía LEVEL a tu ciudad y transforma tu academia en um centro de autoridad internacional.',
    action_student_title: 'QUIERO SER',
    action_student_span: 'ALUMNO',
    action_student_desc: 'Inicia tu viaje en la élite del Jiu Jitsu con instructores maestros y un ambiente de alto nivel.',
    units_title: 'REFERENCIA',
    units_span: 'NACIONAL',
    units_presence: 'NUESTRAS UNIDADES',
    units_btn_all: 'VER TODAS LAS UNIDADES',
    map_locator: 'LOCALIZADOR DE ELITE',
    map_vibe: 'VIVE EL ESTÁNDAR',
    map_desc: 'Presente en la región de Campinas y Jaguariúna. Encuentra la unidad LEVEL más cercana y únete a nuestra comunidad.',
    map_placeholder: 'Tu ubicación (Ciudad o CP)',
    map_btn_search: 'BUSCAR',
    map_open_maps: 'ABRIR EN GOOGLE MAPS',
    map_no_results: 'Ninguna unidad encontrada.',
    store_title: 'LEVEL',
    store_span: 'STORE',
    store_buy: 'COMPRAR AHORA',
    store_filiais: 'A LA VENTA EN LAS FILIALES',
    store_explore: 'EXPLORAR TODA LA COLECCIÓN',
    philosophy_title: 'filosofía soberana',
    philosophy_text: 'NO SE TRATA SÓLO DE LUCHAR.',
    philosophy_sub: 'SE TRATA DE ALCANZAR LA MAESTRÍA.',
    philosophy_message: 'level — desarrollo en el tatami, transformación en la vida',
    news_title: 'MANTENTE DENTRO DEL',
    news_desc: 'Suscríbete a nuestro boletín exclusivo y recibe noticias sobre eventos de élite y nuevos lanzamentos.',
    news_placeholder: 'Tu mejor correo',
    news_btn: 'SUSCRIBIRSE',
    footer_desc: 'Elevando el estándar global a través de uma metodología de élite y um estilo de vida centrado en la soberanía humana.',
    footer_nav: 'NAVEGACIÓN',
    footer_corp: 'CORPORATIVO',
    footer_rights: 'LEVEL JIU JITSU GLOBAL. SOBERANÍA Y TRADICIÓN.'
  }
};

translations.PT.hero_title_suffix = 'Jiu-Jitsu para a Vida';
translations.PT.hero_desc = 'Mais do que um lugar para treinar, um ambiente para evoluir em conjunto.\nUm ambiente onde o Jiu-Jitsu desenvolve pessoas, dentro e fora do tatame.';

Object.assign(translations.PT, {
  about_kicker: 'SOBRE N\u00d3S',
  about_culture_title: 'CULTURA LEVEL',
  about_culture_desc: 'Mais do que um lugar para treinar, um ambiente para evoluir em conjunto.\nUm ambiente onde o Jiu-Jitsu desenvolve pessoas, dentro e fora do tatame.',
  about_culture_card_title: 'CULTURA',
  about_culture_headline: 'Evoluir em conjunto.',
  about_culture_support: 'Jiu-Jitsu que forma pessoas dentro e fora do tatame.',
  about_mission_title: 'MISS\u00c3O LEVEL',
  about_mission_desc: 'Elevar o n\u00edvel do Jiu-Jitsu por meio do desenvolvimento de praticantes, professores e academias, com um sistema estruturado que une forma\u00e7\u00e3o pedag\u00f3gica de qualidade, excel\u00eancia t\u00e9cnica e evolu\u00e7\u00e3o constante.',
  about_mission_card_title: 'MISS\u00c3O',
  about_mission_headline: 'Elevar o n\u00edvel do Jiu-Jitsu.',
  about_mission_support: 'Forma\u00e7\u00e3o pedag\u00f3gica, excel\u00eancia t\u00e9cnica e evolu\u00e7\u00e3o constante.',
  about_base_title: 'NOSSA BASE',
  about_base_highlight: 'A LEVEL \u00e9: m\u00e9todo + t\u00e9cnica + gest\u00e3o.',
  about_base_pillars_title: 'Tr\u00eas pilares fundadores:',
  about_base_card_title: 'BASE',
  about_base_headline: 'M\u00e9todo + t\u00e9cnica + gest\u00e3o.',
  about_base_support: 'M\u00e9todo progressivo, excel\u00eancia t\u00e9cnica e suporte real.',
  about_pillar_1_title: 'M\u00e9todo estruturado e progressivo',
  about_pillar_1_desc: 'constru\u00eddo a partir de pesquisa e desenvolvimento em curr\u00edculo e ensino',
  about_pillar_2_title: 'Excel\u00eancia t\u00e9cnica',
  about_pillar_2_desc: 'liderada por mestres com academias consolidadas',
  about_pillar_3_title: 'Suporte real ao filiado',
  about_pillar_3_desc: 'pedag\u00f3gico, t\u00e9cnico e de gest\u00e3o',
  about_values_title: 'VALORES DA LEVEL',
  about_values_card_title: 'VALORES',
  about_values_headline: 'Uni\u00e3o, m\u00e9todo e evolu\u00e7\u00e3o.',
  about_values_support: 'Consci\u00eancia e compromisso em cada jornada.',
  about_prev: 'ANTERIOR',
  about_next: 'PR\u00d3XIMO',
  about_value_1_title: 'Uni\u00e3o',
  about_value_1_desc: 'Crescer juntos faz parte do processo. Um ambiente de pertencimento que fortalece a evolu\u00e7\u00e3o coletiva.',
  about_value_2_title: 'M\u00e9todo',
  about_value_2_desc: 'M\u00e9todo acima do improviso. Um sistema que organiza o ensino, orienta o treino e sustenta a evolu\u00e7\u00e3o.',
  about_value_3_title: 'Consci\u00eancia',
  about_value_3_desc: 'Saber o que faz, por que faz e como faz. Formamos praticantes que entendem o combate, n\u00e3o apenas reproduzem.',
  about_value_4_title: 'Evolu\u00e7\u00e3o',
  about_value_4_desc: 'Aprimoramento cont\u00ednuo, constru\u00eddo no processo. Nada \u00e9 est\u00e1tico, evolu\u00edmos sempre.',
  about_value_5_title: 'Compromisso',
  about_value_5_desc: 'Evolu\u00e7\u00e3o n\u00e3o \u00e9 acaso, \u00e9 escolha di\u00e1ria. Cada pessoa \u00e9 respons\u00e1vel pela pr\u00f3pria jornada e pelo ambiente.',
});

Object.assign(translations.PT, {
  app_kicker: 'APP LEVEL \u00b7 TREINO NA PALMA DA M\u00c3O',
  app_title_prefix: 'Sua evolu\u00e7\u00e3o, agora',
  app_title_gold: 'no seu bolso.',
  app_desc: 'Acompanhe sua gradua\u00e7\u00e3o, treinos e presen\u00e7as direto pelo celular. O m\u00e9todo LEVEL guiando sua jornada, dentro e fora do tatame.',
  app_btn_download: 'BAIXAR AGORA',
  app_badge_appstore_top: 'Baixar na',
  app_badge_appstore_main: 'App Store',
  app_badge_play_top: 'Dispon\u00edvel no',
  app_badge_play_main: 'Google Play',
  app_chip_1: 'Treinos guiados',
  app_chip_2: '4.9 \u2605 na loja',
});

translations.EN.hero_title_suffix = 'Jiu-Jitsu for Life';
translations.EN.hero_desc = 'More than a place to train, an environment to evolve together.\nA place where Jiu-Jitsu develops people, on and off the mats.';

Object.assign(translations.EN, {
  about_kicker: 'ABOUT US',
  about_culture_title: 'LEVEL CULTURE',
  about_culture_desc: 'More than a place to train, an environment to evolve together.\nA place where Jiu-Jitsu develops people, on and off the mats.',
  about_culture_card_title: 'CULTURE',
  about_culture_headline: 'Evolve together.',
  about_culture_support: 'Jiu-Jitsu that shapes people on and off the mats.',
  about_mission_title: 'LEVEL MISSION',
  about_mission_desc: 'To elevate the level of Jiu-Jitsu through the development of practitioners, instructors, and academies, with a structured system that combines high-quality pedagogical training, technical excellence, and constant evolution.',
  about_mission_card_title: 'MISSION',
  about_mission_headline: 'Elevate the level of Jiu-Jitsu.',
  about_mission_support: 'Pedagogical training, technical excellence, and constant evolution.',
  about_base_title: 'OUR FOUNDATION',
  about_base_highlight: 'LEVEL is: method + technique + management.',
  about_base_pillars_title: 'Three founding pillars:',
  about_base_card_title: 'FOUNDATION',
  about_base_headline: 'Method + technique + management.',
  about_base_support: 'Progressive method, technical excellence, and real support.',
  about_pillar_1_title: 'Structured and progressive method',
  about_pillar_1_desc: 'built from research and development in curriculum and teaching',
  about_pillar_2_title: 'Technical excellence',
  about_pillar_2_desc: 'led by masters with well-established academies',
  about_pillar_3_title: 'Real support for affiliates',
  about_pillar_3_desc: 'pedagogical, technical, and management support',
  about_values_title: 'LEVEL VALUES',
  about_values_card_title: 'VALUES',
  about_values_headline: 'Unity, method, and evolution.',
  about_values_support: 'Awareness and commitment in every journey.',
  about_prev: 'PREVIOUS',
  about_next: 'NEXT',
  about_value_1_title: 'Unity',
  about_value_1_desc: 'Growing together is part of the process. A sense of belonging that strengthens collective evolution.',
  about_value_2_title: 'Method',
  about_value_2_desc: 'Method over improvisation. A system that organizes teaching, guides training, and sustains evolution.',
  about_value_3_title: 'Awareness',
  about_value_3_desc: 'Knowing what you do, why you do it, and how you do it. We develop practitioners who understand combat instead of only reproducing it.',
  about_value_4_title: 'Evolution',
  about_value_4_desc: 'Continuous improvement, built through the process. Nothing is static; we are always evolving.',
  about_value_5_title: 'Commitment',
  about_value_5_desc: 'Evolution is not luck, it is a daily choice. Each person is responsible for their own journey and for the environment around them.',
});

Object.assign(translations.EN, {
  app_kicker: 'LEVEL APP · TRAINING IN YOUR POCKET',
  app_title_prefix: 'Your evolution, now',
  app_title_gold: 'in your pocket.',
  app_desc: 'Track your rank, training, and attendance straight from your phone. The LEVEL method guiding your journey, on and off the mats.',
  app_btn_download: 'DOWNLOAD NOW',
  app_badge_appstore_top: 'Download on the',
  app_badge_appstore_main: 'App Store',
  app_badge_play_top: 'Get it on',
  app_badge_play_main: 'Google Play',
  app_chip_1: 'Guided training',
  app_chip_2: '4.9 ★ on the store',
});

translations.ES.hero_title_suffix = 'Jiu-Jitsu para la Vida';
translations.ES.hero_desc = 'Mas que un lugar para entrenar, un ambiente para evolucionar juntos.\nUn ambiente donde el Jiu-Jitsu desarrolla personas, dentro y fuera del tatami.';

Object.assign(translations.ES, {
  about_kicker: 'SOBRE NOSOTROS',
  about_culture_title: 'CULTURA LEVEL',
  about_culture_desc: 'M\u00e1s que un lugar para entrenar, un ambiente para evolucionar juntos.\nUn ambiente donde el Jiu-Jitsu desarrolla personas, dentro y fuera del tatami.',
  about_culture_card_title: 'CULTURA',
  about_culture_headline: 'Evolucionar juntos.',
  about_culture_support: 'Jiu-Jitsu que forma personas dentro y fuera del tatami.',
  about_mission_title: 'MISI\u00d3N LEVEL',
  about_mission_desc: 'Elevar el nivel del Jiu-Jitsu mediante el desarrollo de practicantes, profesores y academias, con un sistema estructurado que une formaci\u00f3n pedag\u00f3gica de calidad, excelencia t\u00e9cnica y evoluci\u00f3n constante.',
  about_mission_card_title: 'MISI\u00d3N',
  about_mission_headline: 'Elevar el nivel del Jiu-Jitsu.',
  about_mission_support: 'Formaci\u00f3n pedag\u00f3gica, excelencia t\u00e9cnica y evoluci\u00f3n constante.',
  about_base_title: 'NUESTRA BASE',
  about_base_highlight: 'LEVEL es: m\u00e9todo + t\u00e9cnica + gesti\u00f3n.',
  about_base_pillars_title: 'Tres pilares fundadores:',
  about_base_card_title: 'BASE',
  about_base_headline: 'M\u00e9todo + t\u00e9cnica + gesti\u00f3n.',
  about_base_support: 'M\u00e9todo progresivo, excelencia t\u00e9cnica y apoyo real.',
  about_pillar_1_title: 'M\u00e9todo estructurado y progresivo',
  about_pillar_1_desc: 'construido a partir de investigaci\u00f3n y desarrollo en curr\u00edculo y ense\u00f1anza',
  about_pillar_2_title: 'Excelencia t\u00e9cnica',
  about_pillar_2_desc: 'liderada por maestros con academias consolidadas',
  about_pillar_3_title: 'Apoyo real al afiliado',
  about_pillar_3_desc: 'pedag\u00f3gico, t\u00e9cnico y de gesti\u00f3n',
  about_values_title: 'VALORES DE LEVEL',
  about_values_card_title: 'VALORES',
  about_values_headline: 'Unidad, m\u00e9todo y evoluci\u00f3n.',
  about_values_support: 'Conciencia y compromiso en cada camino.',
  about_prev: 'ANTERIOR',
  about_next: 'SIGUIENTE',
  about_value_1_title: 'Unidad',
  about_value_1_desc: 'Crecer juntos forma parte del proceso. Un ambiente de pertenencia que fortalece la evoluci\u00f3n colectiva.',
  about_value_2_title: 'M\u00e9todo',
  about_value_2_desc: 'M\u00e9todo por encima de la improvisaci\u00f3n. Un sistema que organiza la ense\u00f1anza, orienta el entrenamiento y sostiene la evoluci\u00f3n.',
  about_value_3_title: 'Conciencia',
  about_value_3_desc: 'Saber lo que haces, por qu\u00e9 lo haces y c\u00f3mo lo haces. Formamos practicantes que entienden el combate, no solo lo reproducen.',
  about_value_4_title: 'Evoluci\u00f3n',
  about_value_4_desc: 'Perfeccionamiento continuo, construido en el proceso. Nada es est\u00e1tico; siempre evolucionamos.',
  about_value_5_title: 'Compromiso',
  about_value_5_desc: 'La evoluci\u00f3n no es casualidad, es una elecci\u00f3n diaria. Cada persona es responsable de su propio camino y del ambiente.',
});

Object.assign(translations.ES, {
  app_kicker: 'APP LEVEL \u00b7 ENTRENAMIENTO EN TU MANO',
  app_title_prefix: 'Tu evoluci\u00f3n, ahora',
  app_title_gold: 'en tu bolsillo.',
  app_desc: 'Sigue tu graduaci\u00f3n, entrenamientos y asistencias directo desde el m\u00f3vil. El m\u00e9todo LEVEL guiando tu camino, dentro y fuera del tatami.',
  app_btn_download: 'DESCARGAR AHORA',
  app_badge_appstore_top: 'Desc\u00e1rgalo en la',
  app_badge_appstore_main: 'App Store',
  app_badge_play_top: 'Disponible en',
  app_badge_play_main: 'Google Play',
  app_chip_1: 'Entrenamientos guiados',
  app_chip_2: '4.9 \u2605 en la tienda',
});

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('PT');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
